(defpackage #:ngl
  (:use #:common-lisp)
  (:shadow #:structure)
  (:export
    #:ambient-color
    #:ambient-intensity
    #:atom-quad
    #:auto-view
    #:background-color
    #:ball-and-stick
    #:base
    #:camera-eye-sep
    #:camera-fov
    #:camera-type
    #:cartoon
    #:clip-dist
    #:clip-far
    #:clip-mode
    #:clip-near
    #:clip-scale
    #:color-scheme
    #:component
    #:components
    #:dihedral
    #:direction
    #:ext
    #:fog-far
    #:fog-near
    #:frame
    #:fullscreen
    #:hover-timeout
    #:impostor
    #:interpolate-step
    #:interpolate-type
    #:is-running
    #:label-color
    #:label-size
    #:label-visible
    #:label-z-offset
    #:licorice
    #:light-color
    #:light-intensity
    #:measurement
    #:mode
    #:mouse-preset
    #:name
    #:on-pick
    #:on-stage-pick
    #:pan-speed
    #:pause
    #:play
    #:position
    #:positions
    #:quality
    #:quaternion
    #:representation
    #:representations
    #:rock
    #:rotate-speed
    #:sample-level
    #:scale
    #:sele
    #:sphere-detail
    #:spin
    #:stage
    #:%step
    #:stop
    #:structure
    #:structure-representation
    #:timeout
    #:tooltip
    #:trajectories
    #:trajectory
    #:uuid
    #:value
    #:value
    #:visible
    #:worker-default
    #:zoom-speed))

